version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /src/Serilog.Extensions.Formatting
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Serilog.Extensions.Formatting
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /test/Serilog.Extensions.Formatting.Benchmark
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /test/Serilog.Extensions.Formatting.Test
    schedule:
      interval: daily
